### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)

### CODE REVIEW

**Review by kilobyte — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kilobyte and @maciekpac)

___
*[include/memkind/internal/memkind_memtier.h, line 327 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MorU3SB0vJRFx4JB48d:-MorU3SB0vJRFx4JB48e:bezl6jf) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L327)):*
> ```objc
> // it has more influence on ratio
> #define HOTNESS_PEBS_TREAD_FREQUENCY 50.0
> // smaller value -> more frequent sampling
> ```

"FREQUENCY" means higher value → more samples per second; I'd rename the define.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

___
*[include/memkind/internal/memkind_memtier.h, line 266 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MosPhmXAi-T_Bd6ZzGp:-MosPhmXAi-T_Bd6ZzGq:by2dvbi) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L266)):*
> ```objc
> 
> #define DEFAULT_HOTNESS_MEASURE_WINDOW  1000000000 // time window is 1s
> #define DEFAULT_OLD_HOTNESS_WINDOW_WEIGHT  0.4 // time window is 1s
> ```

Fix the comment.
___
*[include/memkind/internal/memkind_memtier.h, line 327 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MosRmuR3NT0WutEdfdz:-MosRmuR3NT0WutEdfe-:b-yapy36) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L327)):*
> ```objc
> // it has more influence on ratio
> #define HOTNESS_PEBS_TREAD_FREQUENCY 50.0
> // smaller value -> more frequent sampling
> ```

The opposite is true: https://github.com/bratpiorka/memkind_hot_poc/blob/cleanup/src/pebs.c#L87-L89. It really is a kind of a frequency.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[include/memkind/internal/memkind_memtier.h, line 266 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MosPhmXAi-T_Bd6ZzGp:-MpLmV3w7myInhiKy2cW:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L266)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Fix the comment.
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_memtier.h, line 327 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MorU3SB0vJRFx4JB48d:-MpLlOTE4iDiXMng87Tz:bb6un1j) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L327)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

"FREQUENCY" means higher value → more samples per second; I'd rename the define.
</blockquote></details>

Done
___
*[include/memkind/internal/memkind_memtier.h, line 327 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MosRmuR3NT0WutEdfdz:-MpLlW0_3LN5A8I34QDD:by86mwh) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/c540212a1b026410a8223ebef028f4dc31f2f481/include/memkind/internal/memkind_memtier.h#L327)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

The opposite is true: https://github.com/bratpiorka/memkind_hot_poc/blob/cleanup/src/pebs.c#L87-L89. It really is a kind of a frequency.
</blockquote></details>

Actually, there are two things: PEBS_SAMPLING_INTERVAL (renamed from PEBS_SAMPLING_FREQUENCY) and BACKGROUND_THREAD_FREQUENCY (renamed from PEBS_THREAD_FREQUENCY.

Please check it now.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

___
*[include/memkind/internal/memkind_memtier.h, line 334 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MpLppCSE1AIFwU-hQ8f:-MpLppCSE1AIFwU-hQ8g:bfhr8j0) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/645bffc6f8d969e6749a1e757a2b7e1bb23717ac/include/memkind/internal/memkind_memtier.h#L334)):*
> ```objc
> // hotness threshold needs to be more up-to-date than pebs touches,
> // it has more influence on ratio
> <<<<<<< HEAD
> ```

Sth went wrong during rebase.
___
*[include/memkind/internal/memkind_memtier.h, line 340 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MpLq2wz0gLz94lTxoO1:-MpLq2wz0gLz94lTxoO2:bz6oaxb) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/645bffc6f8d969e6749a1e757a2b7e1bb23717ac/include/memkind/internal/memkind_memtier.h#L340)):*
> ```objc
> #define HOTNESS_PEBS_SAMPLING_INTERVAL 1000
> =======
> #define HOTNESS_PEBS_TREAD_FREQUENCY 10.0
> ```

THREAD

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/memkind_memtier.h, line 334 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MpLppCSE1AIFwU-hQ8f:-MpLrRiC7p0DtSkDQLvr:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/645bffc6f8d969e6749a1e757a2b7e1bb23717ac/include/memkind/internal/memkind_memtier.h#L334)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Sth went wrong during rebase.
</blockquote></details>

Done.
___
*[include/memkind/internal/memkind_memtier.h, line 340 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21#-MpLq2wz0gLz94lTxoO1:-MpLs8Uu87ZzigJZTvnj:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/645bffc6f8d969e6749a1e757a2b7e1bb23717ac/include/memkind/internal/memkind_memtier.h#L340)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

THREAD
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
