### PR TITLE
[WIP] Swap critnib implementation to use pointers and slab_alloc; bas…

### PR DESCRIPTION
**Pull request by maciekpac**
…ic functionality works, but some features require update

### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28)

### CODE REVIEW

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[include/memkind/internal/critnib.h, line 17 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpKzZpbBIX-Ec9X1ODH:-MpKzZpbBIX-Ec9X1ODI:bqy7sew) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/include/memkind/internal/critnib.h#L17)):*
> ```objc
> 
> enum find_dir_t {
> 	FIND_L  = -2,
> ```

nit: FIND_LT/FIND_GT
___
*[include/memkind/internal/critnib.h, line 30 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpQGbjIDbNz1vEPxT1t:-MpQGbjIDbNz1vEPxT1u:bieursy) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/include/memkind/internal/critnib.h#L30)):*
> ```objc
> void *critnib_remove(critnib *c, uintptr_t key);
> void *critnib_get(critnib *c, uintptr_t key);
> void *critnib_find_le(critnib *c, uintptr_t key);
> ```

Is it still needed given there is a `critnib_find()` function?
___
*[src/critnib.c, line 56 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpL-aaN34RHMbDjKB4y:-MpL-aaN34RHMbDjKB4z:bcsefya) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/src/critnib.c#L56)):*
> ```C
> #include "memkind/internal/critnib.h"
> 
> // eof pmdk-compat.h
> ```

What this comment is about? There is no such file.
___
*[src/critnib.c, line 171 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpQJGKc9cPQX4gx9rAh:-MpQJGKd9744YGs0P7-C:bt1rl4c) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/src/critnib.c#L171)):*
> ```C
> 
> 	/* nodes removed but not yet eligible for reuse */
> 	struct critnib_node *pending_del_nodes[DELETED_LIFE];
> ```

nit: `DELETED_LIFE` -> `MAX_PENDING_DELETED_ITEMS` or sth similar?

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[include/memkind/internal/critnib.h, line 17 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpKzZpbBIX-Ec9X1ODH:-MpRZBqD-9dcrg5ASdPv:b15dbux) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/include/memkind/internal/critnib.h#L17)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: FIND_LT/FIND_GT
</blockquote></details>

This is taken from Adam's repo, I would prefer not to modify it for backwards compatibility
___
*[include/memkind/internal/critnib.h, line 30 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpQGbjIDbNz1vEPxT1t:-MpRZUGN5ZsB346siHX9:b-66vpdh) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/include/memkind/internal/critnib.h#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Is it still needed given there is a `critnib_find()` function?
</blockquote></details>

probably not, but again - I would prefer to keep it for backwards compatibility; The way to go would probably be to modify the repo by Adam?
___
*[src/critnib.c, line 56 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpL-aaN34RHMbDjKB4y:-MpRZlMk5S13CaqXar8T:b-erl55u) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/src/critnib.c#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

What this comment is about? There is no such file.
</blockquote></details>

This is precisely the point - I took some code from this file (original kilobyte's repo) and I pasted relevant parts here. If I remember correctly, the whole file was not compatible with memkind (stuff like #defs for mutexes, etc), so I decided to take only part of it. 

I have updated my comments to make it clear
___
*[src/critnib.c, line 171 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28#-MpQJGKc9cPQX4gx9rAh:-MpR_ZqB4kwiF-zChohg:b-rrwryc) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/4dd8a2fcda11a978ffdc0d2e28b8ed96fd319a89/src/critnib.c#L171)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: `DELETED_LIFE` -> `MAX_PENDING_DELETED_ITEMS` or sth similar?
</blockquote></details>

Again, I prefer not to change this part... Unless kilobyte decides to change the content there as well

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Comment by maciekpac** [comment]
This change has breaks some features used in UT, but tasks for corrections are already set up and I would like to base my other changes on this pull request. Jenkins tests passed.

**Pull request merged**
