### PR TITLE
Counter bench tests and corrections

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [x] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[src/memkind_memtier.c, line 255 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3IDm81pjGVDt2mJnT:-Mo3IDm81pjGVDt2mJnU:b-305eb2) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/6955a3a69d0b9dea35ed8f705b39d3e8cdc7c6a3/src/memkind_memtier.c#L255)):*
> ```C
>             memkind_atomic_get_and_zeroing(t_alloc_size[kind_id][bucket_id]);
>         memkind_atomic_increment(g_alloc_size[kind_id], size_f);
>         size_t total_size = size_f + memkind_atomic_increment(
> ```

???? why? also, in increment_alloc_size this is different

**Review by PatKamin — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 2 unresolved discussions (waiting on @maciekpac)

___
*[src/pebs.c, line 167 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3ITnnEhT4vxpYeNLb:-Mo3ITnnEhT4vxpYeNLc:b-33mznk) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/38b19644d03fa9a0e7917fbf0714c1c19f30c2e2/src/pebs.c#L167)):*
> ```C
>             switch (event.type) {
>                 case EVENT_CREATE_ADD: {
>                     log_debug("EVENT_CREATE_ADD");
> ```

nit: data->address and data->size might be useful in these prints.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

___
*[collect_and_plot.py, line 6 at r4](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3QHKe2JgQ0iBrcLvv:-Mo3QHKe2JgQ0iBrcLvw:bkm8udb) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/e4c6c188f002db81b808c55bb69ea186451b5b16/collect_and_plot.py#L6)):*
> ```Python
> import re
> import matplotlib.pyplot as plt
> ```

Add a comment with the example run from command line.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[collect_and_plot.py, line 6 at r4](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3QHKe2JgQ0iBrcLvv:-Mo3Tv7oCVGNwiWfBBPt:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/e4c6c188f002db81b808c55bb69ea186451b5b16/collect_and_plot.py#L6)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add a comment with the example run from command line.
</blockquote></details>

Done.
___
*[src/memkind_memtier.c, line 255 at r3](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3IDm81pjGVDt2mJnT:-Mo3Wb0kB96-C0QxyfV-:b8fxsx) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/6955a3a69d0b9dea35ed8f705b39d3e8cdc7c6a3/src/memkind_memtier.c#L255)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

???? why? also, in increment_alloc_size this is different
</blockquote></details>

'''size''' is what we increment/decrement

Previously, incorrect value was returned.

We have 3 values: total size (g_alloc_size/total_size), temporary buffer (t_alloc_size, copied to size_f) and current change (size). We update size -> t_alloc_size/size_f -> g_alloc_size; we should not update g_alloc_size/total_size directly with size, but with intermediary buffer (t_alloc_size/size_f).

Detailed workflow:
   1. The value ('''size'''') is first stored in '''t_alloc_size''' (kind of temporary cache) until threshold is passed
   2. '''t_alloc_size''' is read and zeroed (signed value, negative values are also valid)
   3. The read value is applied to g_alloc_size (which is unsigned, total size used cannot be negative)
   4. Total used size should be equal to the value of g_alloc_size (old value + size_f), so this is what should be returned

Thank you for pointing our that increment_alloc_size is different, I updated that function as well.
___
*[src/pebs.c, line 167 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9#-Mo3ITnnEhT4vxpYeNLb:-Mo3Txtk7Jmw0qVboD0p:b-paz1q3) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/38b19644d03fa9a0e7917fbf0714c1c19f30c2e2/src/pebs.c#L167)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: data->address and data->size might be useful in these prints.
</blockquote></details>

I only changed verbosity level (debug vs info), I did not touch the contents, but I applied your remark

**Review by PatKamin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by PatKamin — APPROVED** [review]

**Review by bratpiorka — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
