### PR TITLE
Touch all ttype objects on an event call

### PR DESCRIPTION
**Pull request by PatKamin**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [x] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)

### CODE REVIEW

**Review by maciekpac — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[include/memkind/internal/tachanka.h, line 51 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MmwYPFXUEkrGkBdIgxw-r1-51:-Mna3qhJ-PaiZe6m9yAd:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/2c48496a0f5eced77dda82463278028a853acae3/include/memkind/internal/tachanka.h#L51)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

__u64 is **NOT** uint64_t !

I know it's ridiculous, but look at the definition:
```c
typedef unsigned long int __uint64_t;
__extension__ typedef unsigned long long __u64;
```
both are supposed to denote unsigned 64 bit integer and should work fine (unsigned long and unsigned long long have the same size on most/all 64-bit compilers), but please don't make implicit conversions between one and another, especially with pointers.

values preceeded by two underscores **__** are internal compiler macros/types, not to be directly used by the user - we should handle them with care, using explicit asserts (e.g. for size) when necessary. You can also check *__builtin_types_compatible_p*

</blockquote></details>

Done.
___
*[src/pebs.c, line 283 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MmwYPFXUEkrGkBdIgxx-r1-283:-Mna3rrt32hw2ND2OpTo:b-fgvn5y) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/2c48496a0f5eced77dda82463278028a853acae3/src/pebs.c#L283)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Incorrect place, already mentioned by Rafał during daily meeting.
</blockquote></details>

Please, verify the new place.
___
*[src/tachanka.c, line 398 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MmwYPFXUEkrGkBdIgxy-r1-398:-Mna3vGV6WX194pvlE4o:b4855pb) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/2c48496a0f5eced77dda82463278028a853acae3/src/tachanka.c#L398)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Why ntypes++ ?? Is this loop correct?
</blockquote></details>

Thanks! Done.

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 5 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[test/memkind_memtier_hotness_test.cpp, line 292 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaL3VH487ZQKh4u5y7:-MnaL3VH487ZQKh4u5y8:b-c854ov) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L292)):*
> ```cpp
>         old_freqs[i] = tachanka_get_frequency(i);
>     }
>     tachanka_ranking_touch_all(1, 1e6);
> ```

can you explain here (in comment) what is the scenario here? why do you call this function 4 times with different args and sleep between?
___
*[test/memkind_memtier_hotness_test.cpp, line 298 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLH9N7iYRqvpxh7VG:-MnaLH9N7iYRqvpxh7VH:bfi30v5) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L298)):*
> ```cpp
>     tachanka_ranking_touch_all(3 * hotness_measure_window + 2, 0);
>     for (size_t i = 0; i < MALLOC_COUNT; ++i) {
>         ASSERT_NE(old_freqs[i], tachanka_get_frequency(i));
> ```

so what do you really check here? Maybe both old_freqs and new ones should meet some criteria that you could check in ASSERT_EQ or GT/LT?

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 6 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[test/memkind_memtier_hotness_test.cpp, line 269 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLdlv5P4pG4nL2pwQ:-MnaLdlv5P4pG4nL2pwR:b-s59c02) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L269)):*
> ```cpp
>                         ::testing::Values(3, 20));
> 
> #if RANKING_TOUCH_ALL
> ```

How would this test be run? If we ran it in CI, we'd need a separate build where we'd (probably) be testing more than this one case, so we lose some time running the same tests multiple times.

**Review by maciekpac — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 4 unresolved discussions (waiting on @bratpiorka and @PatKamin)

___
*[src/pebs.c, line 217 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaPDUvBVhpG5SQG-dV:-MnaPDUvBVhpG5SQG-dW:bwlpq5a) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/src/pebs.c#L217)):*
> ```C
> #endif
>             int samples = 0;
>             __u64 timestamp = 0;
> ```

Why is the timestamp set to zero? Is it relevant? Each time it's needed, it should be read from buffer,,,
___
*[test/memkind_memtier_hotness_test.cpp, line 269 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLdlv5P4pG4nL2pwQ:-MnaQg6nEOaYDFq27QV8:b-upobe0) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L269)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

How would this test be run? If we ran it in CI, we'd need a separate build where we'd (probably) be testing more than this one case, so we lose some time running the same tests multiple times.
</blockquote></details>

It can always be run locally, when testing different values....

It might be a problem with regression testing, but at least we would know if the code is broken by another commit if we check it - it's already a lot
___
*[test/memkind_memtier_hotness_test.cpp, line 292 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaL3VH487ZQKh4u5y7:-MnaQ5Ha7SBEyt-04PWL:b-5zb3cr) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L292)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

can you explain here (in comment) what is the scenario here? why do you call this function 4 times with different args and sleep between?
</blockquote></details>

In order to have different timestamps.

Is sleep necessary btw?We provide the timestamp by hand...
___
*[test/memkind_memtier_hotness_test.cpp, line 298 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLH9N7iYRqvpxh7VG:-MnaQQTI2p9BBk8uYviS:b-qzfywb) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L298)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

so what do you really check here? Maybe both old_freqs and new ones should meet some criteria that you could check in ASSERT_EQ or GT/LT?
</blockquote></details>

The fact that the timestamp changes is already an important info, but I agree that checking for greater/lower value would be better; calculating value by hand would probably be best

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @bratpiorka and @maciekpac)

___
*[src/pebs.c, line 217 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaPDUvBVhpG5SQG-dV:-MnddrIN0oXXzywZ7qFa:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/src/pebs.c#L217)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Why is the timestamp set to zero? Is it relevant? Each time it's needed, it should be read from buffer,,,
</blockquote></details>

Done.
___
*[test/memkind_memtier_hotness_test.cpp, line 269 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLdlv5P4pG4nL2pwQ:-MndfWnfDqXbbvcwOCvX:b1hlz49) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L269)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

It can always be run locally, when testing different values....

It might be a problem with regression testing, but at least we would know if the code is broken by another commit if we check it - it's already a lot
</blockquote></details>

Removed #ifdefs
___
*[test/memkind_memtier_hotness_test.cpp, line 292 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaL3VH487ZQKh4u5y7:-Mnf4wIU6i4MhKcpaWAl:b-zcjdpz) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L292)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

In order to have different timestamps.

Is sleep necessary btw?We provide the timestamp by hand...
</blockquote></details>

Added comments. sleep() required in order to wait for memtier_mallocs to be handled by the pebs_monitor().
___
*[test/memkind_memtier_hotness_test.cpp, line 298 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-MnaLH9N7iYRqvpxh7VG:-MnfFGWx1JqGf5s0H7rT:b-9rusn7) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/75df37d82654756b85f7e33ec7914203e0928084/test/memkind_memtier_hotness_test.cpp#L298)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

The fact that the timestamp changes is already an important info, but I agree that checking for greater/lower value would be better; calculating value by hand would probably be best
</blockquote></details>

Checking frequencies several times now.
Decided to stick with the GT condition. Calculating by hand would depend on the `old_time_window_hotness_weight` variable which is set in builder_hot_create_memory(). I don't want to introduce tracking of another variable (I already had to include in this test `hotness_measure_window` - when this value will be increased in the builder_hot_create_memory(), the test could fail).

**Review by bratpiorka — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by bratpiorka — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac and @PatKamin)

___
*[src/pebs.c, line 326 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-Mnk4-N3BbuSoSmr3vCV:-Mnk4-N3BbuSoSmr3vCW:b2a2a5j) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/238a306ccb7c6d721a41b22582af8f56c8c5105d/src/pebs.c#L326)):*
> ```C
> #if RANKING_TOUCH_ALL
>             // Touch every ttype object to update hotness
>             if (timestamp > 0) {
> ```

Why only if higher than zero?

If it matters, maybe a comment would be a good idea?
___
*[test/memkind_memtier_hotness_test.cpp, line 292 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-Mnk52XmAptTzYZBmyo0:-Mnk52XmAptTzYZBmyo1:b-akczq3) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/238a306ccb7c6d721a41b22582af8f56c8c5105d/test/memkind_memtier_hotness_test.cpp#L292)):*
> ```cpp
> 
>     
>     sleep(1); // wait for pebs_monitor() to register new types from memtier_mallocs
> ```

We've had a discussion about this sleep synchronisation - for now, we decided it can just stay this way

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

___
*[src/pebs.c, line 326 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-Mnk4-N3BbuSoSmr3vCV:-Mnk5uiR5gXxn7BDg47A:b-re19ae) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/238a306ccb7c6d721a41b22582af8f56c8c5105d/src/pebs.c#L326)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

Why only if higher than zero?

If it matters, maybe a comment would be a good idea?
</blockquote></details>

I wanted to make sure that the timestamp will always be set to some non-zero value. Meaning that the flow entered the switch with events. Perhaps it will never be 0 and this check could be removed. Just wasn't sure ,that's why I added this.
___
*[test/memkind_memtier_hotness_test.cpp, line 292 at r5](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6#-Mnk52XmAptTzYZBmyo0:-Mnk6YIs2bh2ep1yBURe:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/238a306ccb7c6d721a41b22582af8f56c8c5105d/test/memkind_memtier_hotness_test.cpp#L292)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

We've had a discussion about this sleep synchronisation - for now, we decided it can just stay this way
</blockquote></details>

Done.

**Review by bratpiorka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Pull request merged**
