### PR TITLE
Upgrade hotness calculation - use exponential decay

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [x] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [x] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12)

### CODE REVIEW

**Review by bratpiorka — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12)* status: all files reviewed, 3 unresolved discussions (waiting on @maciekpac)

___
*[include/memkind/internal/memkind_memtier.h, line 315 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZFJHY13wYW4ctoaLl:-MoZFJHY13wYW4ctoaLm:b-7yulx8) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/include/memkind/internal/memkind_memtier.h#L315)):*
> ```objc
> 
> // TODO maybe hotness should be recalculated more often than all other
> // pebs operations? add some kind of simple sub-scheduler for this thread?
> ```

Why? 
___
*[src/pebs.c, line 271 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZIBML-FjL5YIn7_30:-MoZIBML-FjL5YIn7_31:b-yeqz64) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/src/pebs.c#L271)):*
> ```C
>                     {
>                         // TODO is this really correct? Check init and layout
>                         // of PERF_RECORD_SAMPLE docs; add explanation/fix
> ```

content of this struct is defined by "pe.sample_type = PERF_SAMPLE_ADDR | PERF_SAMPLE_TIME" in  pebs_init()
___
*[src/tachanka.c, line 92 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZIshjCkSiHr6sLPGV:-MoZIshjCkSiHr6sLPGW:btunmz6) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/src/tachanka.c#L92)):*
> ```C
>         memset(t, 0, sizeof(t[0]));
> 
> //         bigary_alloc(&ba_ttypes, nt*sizeof(struct ttype));
> ```

why this is commented?

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @bratpiorka)

___
*[include/memkind/internal/memkind_memtier.h, line 315 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZFJHY13wYW4ctoaLl:-Mocwapm1ZOOES5SOjgT:bd5ikum) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/include/memkind/internal/memkind_memtier.h#L315)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Why? 
</blockquote></details>

Comment was extended: hotness threshold needs to be more up-to-date than pebs touches, it has more influence on ratio
___
*[src/pebs.c, line 271 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZIBML-FjL5YIn7_30:-Mocxlhy353QkOGlmpcg:bhywcgy) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/src/pebs.c#L271)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

content of this struct is defined by "pe.sample_type = PERF_SAMPLE_ADDR | PERF_SAMPLE_TIME" in  pebs_init()
</blockquote></details>

I copy-pasted this comment to code
___
*[src/tachanka.c, line 92 at r2](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-MoZIshjCkSiHr6sLPGV:-MocxwYx1_cSbqzWFl4r:b-jmpjo4) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/af362811193fd74e7ee3b81e72d3edb133da76a0/src/tachanka.c#L92)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why this is commented?
</blockquote></details>

my bad, uncommented and reordered

**Review by bratpiorka — COMMENTED** [review]
> Reviewed 4 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by bratpiorka — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/12#-:-Mod3Om_3abtbf2bQsWx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
