### PR TITLE
Add code for heatmap creation and parsing

### PR DESCRIPTION
**Pull request by maciekpac**
### Types of changes

- [ ] Bugfix (non-breaking change which fixes issue linked in Description above)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [ ] Other

### Checklist

- [ ] Code compiles without errors
- [ ] All tests pass locally with my changes (see TESTING section in CONTRIBUTING file)
- [ ] Created tests which will fail without the change (if possible)
- [ ] Extended the README/documentation (if necessary)
- [ ] All newly added files have proprietary license (if necessary)
- [ ] All newly added files are referenced in MANIFEST files (if necessary)

## Further comments

---
This change is [Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

___
*[parse_heatmap.py, line 53 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32#-MpkUdo4BSzyqAuR2fX7:-MpkUdo4BSzyqAuR2fX8:b-8l1lx7) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/d2c9fcec975e8a6679c70b0045e28ba437ee8f79/parse_heatmap.py#L53)):*
> ```Python
> ax[1].imshow(dram_total_heat, cmap='hot', interpolation='nearest')
> ax[1].set_title('Dram to total heatmap')
> plt.show()
> ```

Please, add saving the plot to a file and put some kind of a legend or comment at least.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[parse_heatmap.py, line 53 at r1](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32#-MpkUdo4BSzyqAuR2fX7:-Mpl-rvO9y16-vx4ICbI:b-896fix) ([raw file](https://github.com/bratpiorka/memkind_hot_poc/blob/d2c9fcec975e8a6679c70b0045e28ba437ee8f79/parse_heatmap.py#L53)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Please, add saving the plot to a file and put some kind of a legend or comment at least.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bratpiorka/memkind_hot_poc/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
